### ISSUE TITLE
webpack build script

### ISSUE THREAD

**Issue by sbreiler** [chevalvert/boilerplate-php-webpack#1]
Hi,

first of all, nice repo - thanks for that!

I run into a problem using the `webpack-build.js` script. Bundle-Files didn't got updated, but no error was shown either. Also, it showed "Success: Build completed".

I finally realized my javascript had errors.

Following change did the trick for me, at https://github.com/chevalvert/boilerplate-php-webpack/blob/master/scripts/webpack-build.js#L27`:
```javascript
	if( err ) {
		reject(err);
	}
	else {
		if( stats.hasErrors() ) {
			sh.error('Error during the webpack compilation');

			stats.compilation.errors.map(sh.error);
			stats.compilation.children.map(child => {
				const childStats = child.getStats();
				childStats.compilation.errors.map(sh.error);
				childStats.compilation.warnings.map(sh.warn);
			});

			sh.exit(0);
		}
		else {
			if( stats.hasWarnings() ) {
				sh.log('Compile warnings');
				stats.compilation.warnings.map(sh.warn);
				stats.compilation.children.map(child => {
					child.getStats().compilation.warnings.map(sh.warn);
				});
			}
			resolve(stats);
		}
	}
```

Maybe you want to change it in your repo too.

**Comment by arnaudjuracek** [comment]
Hey, thanks for that ! 
Would you mind creating a PR so that I can merge your changes ?

**Comment by sbreiler** [comment]
I created a PR just now - i tried to resamble youre coding style.

It also shows warnings now. It seems errors are displayed twice "most" of the time... better twice than none, i guess.

**Comment by arnaudjuracek** [comment]
Thanks !
